export const ADD_TO_BREAD_CRUMB_PATH = "ADDUSERTOBREADCRUMBPATH";
export const SET_CURRENT_CONTENT = "SETCURRENTCONTENT";
export const SET_INITIAL_CONTENT = "SETINITIALCONTENT";
export const SET_INITIAL_TODOS = "SETINITIALTODOS";
export const GET_ALL_TODOS = "GET-ALL-TODOS";
export const ADD_TODO = "ADD_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const DELETE_TODO = "DELETE_TODO";